kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: storage-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc
