apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: dexoid/homework1:v2
    volumeMounts:
    - mountPath: "/data"
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data
